"""add otp columns to users

Revision ID: 68de84842004
Revises: a1832cbb00b5
Create Date: 2026-06-08 14:16:59.437523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68de84842004'
down_revision: Union[str, Sequence[str], None] = 'a1832cbb00b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('otp_expiry', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_expiry')
    op.drop_column('users', 'otp_code')
    # ### end Alembic commands ###
